[
  {
    "commonName": "African Violet",
    "scientificName": "Saintpaulia ionantha",
    "lightNeeds": "African Violet plants do best and flower more in  bright indirect lightVery few houseplants should be placed in direct sun. High light refers only to bright indirect light since direct sun often burns the leaves of indoor houseplants. An area that is too hot and dry encourages Spider Mites and causes blooms to quickly fade. A northern exposure really doesn't provide enough light for high light plants. These plants need to be placed directly in front of an east-facing window, within 1-3 feet of a west-facing window, and within 5 ft. of a south facing window. A high light area has over 300 ft. candles of light., close to an east-facing window is ideal. When the light is too low, the leaves turn dark green, lose their plump appearance, and the plant produces very few flowers. The leaves turn a pale yellow-green and the flowers fade quickly when there is too much light.",
    "waterNeeds": "Allow the top 1\"- 2\" of soil to dry out before watering. Avoid using water that has passed through a softener or water containing chlorine or fluoride. Always water African Violet houseplants from the bottom to prevent water getting on the leaves. Remove any excess water that is still in the saucer after 15 minutes.",
    "tempNeeds": "These plants do well in temperatures of 75°-80°F (23.9°-26.7C) during the day and about 10° cooler at night. Keep African Violet plants away from cold drafts and heating vents. High humidity is preferable, but African Violets easily adapt to basic household humidity.",
    "soilNeeds": "African Violets like a rich, airy, potting medium. Special African Violet soil is available at most garden centers. These plants should be re-potted every 6-12 months using fresh soil to prevent unwanted salt build-up.",
    "potSize": "Keep African Violets a little root-bound in a small pot. This encourages the plant to produce more flowers.",
    "poisonous": "African Violets are non-  Poisonous HouseplantsIn her new book, Don’t Feed Me to Your Cat!,  plant care professional Judy Feldstein shares information about twenty-five common houseplants, each with various levels of toxicity, and the possible consequences if your pet or child snacks on them.."
  }
]